# Generated by Django 4.0.4 on 2022-06-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='favorite_artists',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='favorite_playlists',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='favorite_shows',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='favorite_tracks',
            new_name='favorites',
        ),
    ]
