# Generated by Django 4.0.4 on 2022-06-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0002_rename_favorite_artists_artist_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='tracks',
        ),
    ]
