# Generated by Django 4.0.4 on 2022-06-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0005_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='audio_url',
            new_name='url',
        ),
    ]
