# Generated by Django 4.0.5 on 2022-06-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0006_rename_audio_url_track_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='closed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='opened',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='closed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='opened',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='livetapes_api.show'),
        ),
    ]
