# Generated by Django 4.0.5 on 2022-06-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0007_note_closed_note_opened_request_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
