# Generated by Django 4.0.5 on 2022-06-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0008_track_track_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='title',
        ),
    ]
