# Generated by Django 4.0.5 on 2022-06-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0009_rename_name_track_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['track_number']},
        ),
    ]
