# Generated by Django 4.0.5 on 2022-06-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetapes_api', '0010_alter_track_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
    ]
